local_costmap:
  global_frame: map
  robot_base_frame: base_link

  update_frequency: 100.0
  publish_frequency: 100.0
  transform_tolerance: 10

  static_map: false  
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
