# 全局地图配置文件
global_costmap:
  # 全局参考坐标系
  global_frame: map
  # 机器人底座坐标系
  robot_base_frame: base_link
  # 全局地图更新频率
  update_frequency: 10.0
  # 地图发布频率
  publish_frequency: 10.0
  # 坐标转换延迟时间
  transform_tolerance: 2.0
  # 是否是静态地图
  static_map: true
 
