# 局部地图配置文件
local_costmap:
  # 局部地图坐标系
  global_frame: odom
  # 机器人底座坐标系
  robot_base_frame: base_link
  # 更新频率
  update_frequency: 10.0
  # 地图发布频率
  publish_frequency: 10.0
  # 坐标转换延迟时间
  transform_tolerance: 2.0  
  # 是否是静态地图
  static_map: false  
  # 地图是否随着机器人移动而改变
  rolling_window: true
  # 滚动窗口大小
  width: 3
  height: 3
  # 分辨率
  resolution: 0.05
  
